const {chromium}=require('playwright');
const {spawn,execFileSync}=require('node:child_process');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const {setTimeout:delay}=require('node:timers/promises');
const origin='http://127.0.0.1:'+(process.env.TEST_PORT||'18080');
const probe=file=>JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));
(async()=>{
 fs.mkdirSync('tests/output',{recursive:true});
 execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','color=c=purple:s=640x360:d=15','-f','lavfi','-i','sine=frequency=440:duration=15','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest','-y','tests/output/finale.mp4']);
 execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=220:duration=3','-y','tests/output/music.wav']);
 const server=spawn('python',['main.py'],{env:{...process.env,PORT:new URL(origin).port},stdio:'ignore'});
 let browser;
 try{
  let ready=false;for(let n=0;n<100;n++){if(server.exitCode!==null)throw Error('Server exited '+server.exitCode);try{const response=await fetch(origin+'/api/health');if(response.ok){ready=true;break}}catch{}await delay(100)}
  assert.ok(ready,'server did not start');
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{globalThis.structuredClone=undefined});
  await page.goto(origin+'/');assert.ok(page.url().endsWith('/login'));
  await page.fill('[name=username]','admin');await page.fill('[name=password]','admin123');await page.click('button[type=submit]');
  await page.waitForFunction(()=>document.querySelector('#status')?.textContent.startsWith('Ready.'));
  assert.equal(await page.locator('.scene').count(),5);
  assert.equal(await page.inputValue('#lower'),'2500');
  assert.equal(await page.inputValue('#upper'),'3000');
  assert.equal(await page.locator('#rankName').textContent(),'Gold III → Diamond I');
  await page.fill('#score','3075');
  assert.equal(await page.inputValue('#lower'),'3000');
  assert.equal(await page.inputValue('#upper'),'3500');
  await page.fill('#score','2683');
  await page.selectOption('#format','original');
  const [referenceFrame]=await Promise.all([page.waitForEvent('download'),page.click('#png')]);
  await referenceFrame.saveAs('tests/output/aligned-frame.png');
  await page.selectOption('#format','vertical');
  await page.selectOption('#quality','720');await page.selectOption('#celebration','masters');
  await page.screenshot({path:'tests/output/desktop.png',fullPage:true});
  await page.click('#export');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('MP4 ready'),null,{timeout:120000});
  const [first]=await Promise.all([page.waitForEvent('download'),page.click('#download')]);await first.saveAs('tests/output/clip.mp4');
  const sample=probe('tests/output/clip.mp4');const video=sample.streams.find(s=>s.codec_type==='video');
  assert.equal(video.codec_name,'h264');assert.equal(video.width,720);assert.equal(video.height,1280);
  assert.ok(Number(sample.format.duration)>12&&Number(sample.format.duration)<14,'five scenes and endcard duration');
  // The two frames of a single scene must differ because zoom is applied to every image.
  execFileSync('ffmpeg',['-v','error','-ss','0.2','-i','tests/output/clip.mp4','-frames:v','1','-y','tests/output/early.png']);
  execFileSync('ffmpeg',['-v','error','-ss','1.7','-i','tests/output/clip.mp4','-frames:v','1','-y','tests/output/late.png']);
  assert.notDeepEqual(fs.readFileSync('tests/output/early.png'),fs.readFileSync('tests/output/late.png'));
  await page.click('#add');assert.equal(await page.locator('.scene').count(),6);await page.click('#delete');
  const [project]=await Promise.all([page.waitForEvent('download'),page.click('#save')]);await project.saveAs('tests/output/project.json');
  await page.fill('#score','8000');await page.setInputFiles('#projectFile','tests/output/project.json');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Project loaded.'));
  assert.notEqual(await page.inputValue('#score'),'8000');
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/output/mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  // Full 15-second user ending, with audio, attached to a 1-second zoom scene.
  await page.setInputFiles('#icons','static/template.png');await page.waitForFunction(()=>document.querySelector('#leftIcon').options.length===3);
  await page.selectOption('#leftIcon',{index:2});
  while(await page.locator('.scene').count()>1)await page.click('#delete');
  await page.selectOption('#seconds','1');await page.selectOption('#format','original');
  await page.setInputFiles('#musicFile','tests/output/music.wav');
  await page.setInputFiles('#finalFile','tests/output/finale.mp4');
  assert.equal(await page.inputValue('#celebration'),'custom');
  await page.click('#export');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('MP4 ready'),null,{timeout:120000});
  const [second]=await Promise.all([page.waitForEvent('download'),page.click('#download')]);await second.saveAs('tests/output/audio-final.mp4');
  const result=probe('tests/output/audio-final.mp4');
  assert.ok(Number(result.format.duration)>=15.7&&Number(result.format.duration)<16.5,'complete 15-second ending');
  assert.ok(result.streams.some(s=>s.codec_type==='audio'&&s.codec_name==='aac'),'ending audio preserved');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,firstSeconds:sample.format.duration,finalSeconds:result.format.duration,video:video.codec_name,audio:'aac',browserErrors:errors}));
 }finally{if(browser)await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exitCode=1});
