const {chromium}=require('playwright');
const {spawn,execFileSync}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 fs.mkdirSync('tests/output',{recursive:true});
 execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','color=c=purple:s=640x360:d=1','-f','lavfi','-i','sine=frequency=440:duration=1','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest','-y','tests/output/finale.mp4']);
 execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=220:duration=3','-y','tests/output/music.wav']);
 const port=process.env.TEST_PORT||'80';
 const server=spawn('python',['main.py'],{env:{...process.env,PORT:port},stdio:['ignore','pipe','pipe']});
 let browser;
 try {
  await new Promise((res,rej)=>{server.stdout.once('data',res);server.once('exit',code=>rej(new Error('Server exited '+code)))});
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{const orig=MediaRecorder.isTypeSupported.bind(MediaRecorder);MediaRecorder.isTypeSupported=t=>!t.includes('mp4')&&orig(t)});
  await page.goto('http://127.0.0.1:'+port);
  await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Template pronto'));
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.scene').count(),5);
  await page.selectOption('#quality','720');
  await page.selectOption('#celebration','masters');
  await page.screenshot({path:'tests/output/desktop.png',fullPage:true});
  await page.click('#export');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('MP4 pronto'),{},{timeout:120000});
  const [download]=await Promise.all([page.waitForEvent('download'),page.click('#download')]);
  await download.saveAs('tests/output/clip.mp4');
  const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json','tests/output/clip.mp4'],{encoding:'utf8'}));
  const video=probe.streams.find(s=>s.codec_type==='video');
  assert.equal(video.codec_name,'h264');assert.equal(video.width,720);assert.equal(video.height,1280);assert.ok(Number(probe.format.duration)>11);
  await page.selectOption('#format','original');
  assert.equal(await page.locator('#canvas').evaluate(c=>c.width),1080);
  assert.equal(await page.locator('#canvas').evaluate(c=>c.height),720);
  await page.click('#add');assert.equal(await page.locator('.scene').count(),6);
  await page.click('#delete');assert.equal(await page.locator('.scene').count(),5);
  await page.click('#play');await page.click('#cancel');
  await page.waitForFunction(()=>!document.querySelector('#export').disabled);
  const [project]=await Promise.all([page.waitForEvent('download'),page.click('#save')]);
  await project.saveAs('tests/output/project.json');
  await page.fill('#score','8000');
  await page.setInputFiles('#projectFile','tests/output/project.json');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Projeto aberto')||document.querySelector('#status').textContent.startsWith('Template pronto'));
  await page.waitForTimeout(300);
  assert.notEqual(await page.inputValue('#score'),'8000');
  await page.setViewportSize({width:390,height:844});
  await page.selectOption('#format','vertical');
  await page.screenshot({path:'tests/output/mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  // Exercise uploaded rank images, music and a real video finale together.
  await page.setInputFiles('#icons','static/template.png');
  await page.waitForFunction(()=>document.querySelector('#leftIcon').options.length===2);
  await page.selectOption('#leftIcon',{index:1});
  while(await page.locator('.scene').count()>1)await page.click('#delete');
  await page.selectOption('#seconds','1');
  await page.selectOption('#format','original');
  await page.setInputFiles('#musicFile','tests/output/music.wav');
  await page.waitForFunction(()=>document.querySelector('#musicName').textContent==='music.wav');
  await page.setInputFiles('#finalFile','tests/output/finale.mp4');
  await page.waitForFunction(()=>document.querySelector('#finalName').textContent==='finale.mp4');
  await page.click('#export');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('MP4 pronto'),{},{timeout:120000});
  const [second]=await Promise.all([page.waitForEvent('download'),page.click('#download')]);
  await second.saveAs('tests/output/audio-final.mp4');
  const audioProbe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json','tests/output/audio-final.mp4'],{encoding:'utf8'}));
  assert.ok(audioProbe.streams.some(s=>s.codec_type==='audio'&&s.codec_name==='aac'));
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,width:video.width,height:video.height,codec:video.codec_name,duration:probe.format.duration,bytes:fs.statSync('tests/output/clip.mp4').size,browserErrors:errors}));
 }finally{if(browser)await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exit(1)});
